name: CD Pipeline
on:
  pull_request:
    types:
    - closed
    branches:
    - master
jobs: 
  Lint-Test-Build-Application: 
    name: Lint & Run Jest
    runs-on: 
     labels: self-hosted
    steps: 
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.5.0
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: darkdesignx/app:latest